### ISSUE TITLE
Can you add more details in data collection implementation?

### ISSUE THREAD

**Issue by Norweig1an** [sizhe-li/DexDeform#1]
HI DexDeform team,

Thank you for your contribution, and I am astounded by the method you use to collect data in the absence of objects.
Is there any advice on how to build a data collection system, or will you release the code later? It's difficult to follow your work without these guidences. If you could provide some references or explanations in details, I would greatly appreciate it.

**Comment by sizhe-li** [comment]
Thank you for your informative question! I will release the code soon :)

It sounds like you are interested in the teleoperation of a dexterous robotic hand. I would like to expand a bit on the available options.

Our teleoperation system is built on a hand-tracking device called [Leap Motion](https://www.ultraleap.com/), priced at around $200. Our implementation matches the detected angles of a (human) finger skeleton with the joint angles of a shadow hand for demo collection.

There are other solutions that you can consider with off-the-shelf cameras (e.g., iPhone). To detect human hand poses, you can use [FrankMocap ](https://github.com/facebookresearch/frankmocap). See [this work](https://yzqin.github.io/dex-teleop-imitation/) by Qin et al and its related work.

**Comment by Norweig1an** [comment]
Thanks for your response, looking forward to your code release.

**Comment by sizhe-li** [comment]
@Norweig1an I have added the leap motion tracking implementations. It shows how we convert the detected human hand poses into joint angles for the shadow robot hand. [This repo](https://github.com/szahlner/shadow-teleop/tree/main/leap_motion) is also a great resource.

After installing `leap_motion/setup.py,` `leap_motion/tracking/main.py` is a demo that creates a shadow hand environment in PyBullet, and allows you to teleoperate the hand via leap motion hand detection.

(Coming soon) I will add more documentation and support for controlling the shadow hand in our deformable simulation.

**Comment by yl-wang996** [comment]
Hi, I am wondering, is your leap_motion module depends on the Windows system as [this repo](https://github.com/szahlner/shadow-teleop/tree/main/leap_motion)?

**Comment by sizhe-li** [comment]
Leap Motion Library has undergone lots of changes. I am not sure about the latest version.

My implementation currently depends on the Windows system but should be easily adaptable to Linux if you build Leap SDK in Linux.
