### ISSUE TITLE
Mismatch between visualization in paper/website and in code

### ISSUE THREAD

**Issue by YanjieZe** [sizhe-li/DexDeform#2]
Hi Sizhe,
It seems the visualization in your website and paper is more detailed and complex (the hand is more fine-grained, and the arm is provided), while as the code provides, the hand is a simplified version and the arm is removed.

Could you possibly describe how to get the similar visualization as your paper/teaser?

Thank you!

Yanjie

**Comment by sizhe-li** [comment]
Hi Yanjie,

The collision geometry of the current implementation is taken directly from Shadow Robot official configuration. These collision bodies are the same ones used by popular engines such as MuJoCo, PyBullet, and IsaacGym. 

Our visualizations were created with a different renderer. But the underlying physics engine is exactly the same as the current implementation provides. Specifically, we used [SAPIEN](https://sapien.ucsd.edu/) to create higher quality renderings for visualization purpose only, given that our paper assumes point cloud input. I am happy to provide an example for this later! But the rendering speed is much slower. 

For computational efficiency, the arm is not included in the current implementation. Our proposed tasks also do not use the arm.

Let me know if you have any other questions! Thanks!

Sizhe

**Comment by YanjieZe** [comment]
Hi Sizhe,

Thanks for the explanation! It would be very good if an example could be provided. I will stay tuned.

My other questions have been addressed :)

Thank you!

Yanjie
