### ISSUE TITLE
How to get the score of the task?

### ISSUE THREAD

**Issue by YanjieZe** [sizhe-li/DexDeform#3]
Hi Sizhe,

In your paper, you use the EMD to measure the task progress. How can I get that in your provided code?

Thank you!

Yanjie

**Comment by sizhe-li** [comment]
Hi Yanjie,

I just added an [example](https://github.com/sizhe-li/DexDeform/blob/main/tutorials/4_computing_score.ipynb) for computing the EMD. Please first install the required packages I listed in the README.

```bash
pip install pykeops
pip install geomloss
```

Let me know if you have any other questions. Thanks!

Sizhe

**Comment by YanjieZe** [comment]
Thank you, Sizhe!
Could you also provide the target shape file of each task for computing the score? Or you think it is just self-contained in the demonstration, so not necessary?

**Comment by sizhe-li** [comment]
Hi Yanjie,

You are right! We split the demonstrations into train and test folders. The configurations are now uploaded to [here](https://github.com/sizhe-li/DexDeform/tree/main/assets/training).

Within test demonstrations, we use the shapes achieved in the final states for evaluation. As specified in the [demonstration loading tutorial](https://github.com/sizhe-li/DexDeform/blob/main/tutorials/3_demonstration_loading.ipynb), a state is stored as a tuple of arrays. The first element of the tuple represents the particle state of the soft materials. *I am working on a cleaner implementation with more annotations for the states.*

**Some personal tips** - I assume you are working on a fun project :) 
- Of course, you can also download novel shapes from ShapeNet and express them as targets for research purposes! I have personally explored this. 
- You can also specify target shapes by geometrically transforming the ones recorded in the demonstration (i.e., SE3 transform)

Hope this helps. Thanks!

Sizhe

**Comment by YanjieZe** [comment]
Hi Sizhe,

Thank you for all these informative suggestions! 

And yes, the illustrations for these states would be good!

Nice work!

Best

Yanjie Ze

**Comment by sizhe-li** [comment]
Hi Yanjie,

Here is more details for the state tuple that is of length 25. Hope it helps. Thanks!

```
[First Four Elements (ref: https://arxiv.org/pdf/1810.01054.pdf)]

(0) x: positions of all material points, shape (N, 3)
(1) v: velocities of all material points, shape (N, 3)
(2) F: defomration gradient of all material points, shape (N, 3, 3)
(3) C: Affine velocity field, shape (N, 3, 3)

(4-22): Rigid body poses for the 19 primitive shapes. 
Each pose is stored as position (3,) + quaternion rotation (4,)  
...
...
...

(23): base pose of the shadow hand; shape (n_hand, 4, 4)
(24): joint positions of the shadow hand; shape (n_hand, 24)
```

**Comment by YanjieZe** [comment]
Thank you Sizhe!
This is very useful!
