### ISSUE TITLE
When will the algorithm be released?

### ISSUE THREAD

**Issue by yl-wang996** [sizhe-li/DexDeform#4]
Hi, I am trying to replicate this work, I am wondering when will the Dexdeform be released?

**Comment by sizhe-li** [comment]
Hi Yunlong, I am still working on cleaning up the codebase. I could send you a work-in-progress version now if you tell me your email. The implementation will be slightly messy, but it will give you enough information on the policy part.

Sorry, the start of grad school has been busy. Thanks for your understanding!

**Comment by yl-wang996** [comment]
I will be really appreciate it, if you can send me the draft version. My email is yunlong.wang@studium.uni-hamburg.de 
By the way, I do enjoy your work.

**Comment by sizhe-li** [comment]
Thanks - sent!
